# Name of website
title: Neural Networks Project

# Short description of your site
description: Dataset Analysis and CNN Models Optimization for Plant Disease Classification

# Theme
theme: jekyll-theme-cayman
